export const htmlLanguage = {
  ABKHAZIAN: "ab",
  AFAR: "aa",
  AFRIKAANS: "af",
  AKAN: "ak",
  ALBANIAN: "sq",
  AMHARIC: "am",
  ARABIC: "ar",
  ARAGONESE: "an",
  ARMENIAN: "hy",
  ASSAMESE: "as",
  AVARIC: "av",
  AVESTAN: "ae",
  AYMARA: "ay",
  AZERBAIJANI: "az",
  BAMARA: "bm",
  BASHKIR: "ba",
  BASQUE: "eu",
  BELARUSIAN: "be",
  "BENGALI (BANGLA)": "bn",
  BIHARI: "bh",
  BISLAMA: "bi",
  BOSNIAN: "bs",
  BRETON: "br",
  BULGARIAN: "bg",
  BURMESE: "my",
  CATALAN: "ca",
  CHAMORRO: "ch",
  CHECHEN: "ce",
  "CHICHEWA, CHEWA, NYANJA": "ny",
  CHINESE: "zh",
  "CHINESE (SIMPLIFIED)": "zh-Hans",
  "CHINESE (TRADITIONAL)": "zh-Hant",
  CHUVASH: "cv",
  CORNISH: "kw",
  CORSICAN: "co",
  CREE: "cr",
  CROATIAN: "hr",
  CZECH: "cs",
  DANISH: "da",
  "DIVEHI, DHIVEHI, MALDIVIAN": "dv",
  DUTCH: "nl",
  DZONGKHA: "dz",
  ENGLISH: "en",
  ESPERANTO: "eo",
  ESTONIAN: "et",
  EWE: "ee",
  FAROESE: "fo",
  FIJIAN: "fj",
  FINNISH: "fi",
  FRENCH: "fr",
  "FULA, FULAH, PULAAR, PULAR": "ff",
  GALICIAN: "gl",
  "GAELIC (SCOTTISH)": "gd",
  "GAELIC (MANX)": "gv",
  GEORGIAN: "ka",
  GERMAN: "de",
  GREEK: "el",
  GREENLANDIC: "kl",
  GUARANI: "gn",
  GUJARATI: "gu",
  "HAITIAN CREOLE": "ht",
  HAUSA: "ha",
  HEBREW: "he",
  HERERO: "hz",
  HINDI: "hi",
  "HIRI MOTU": "ho",
  HUNGARIAN: "hu",
  ICELANDIC: "is",
  IDO: "io",
  IGBO: "ig",
  INDONESIAN: "id, in",
  INTERLINGUA: "ia",
  INTERLINGUE: "ie",
  INUKTITUT: "iu",
  INUPIAK: "ik",
  IRISH: "ga",
  ITALIAN: "it",
  JAPANESE: "ja",
  JAVANESE: "jv",
  "KALAALLISUT, GREENLANDIC": "kl",
  KANNADA: "kn",
  KANURI: "kr",
  KASHMIRI: "ks",
  KAZAKH: "kk",
  KHMER: "km",
  KIKUYU: "ki",
  "KINYARWANDA (RWANDA)": "rw",
  KIRUNDI: "rn",
  KYRGYZ: "ky",
  KOMI: "kv",
  KONGO: "kg",
  KOREAN: "ko",
  KURDISH: "ku",
  KWANYAMA: "kj",
  LAO: "lo",
  LATIN: "la",
  "LATVIAN (LETTISH)": "lv",
  "LIMBURGISH (LIMBURGER)": "li",
  LINGALA: "ln",
  LITHUANIAN: "lt",
  "LUGA-KATANGA": "lu",
  "LUGANDA, GANDA": "lg",
  LUXEMBOURGISH: "lb",
  MANX: "gv",
  MACEDONIAN: "mk",
  MALAGASY: "mg",
  MALAY: "ms",
  MALAYALAM: "ml",
  MALTese: "mt",
  MAORI: "mi",
  MARATHI: "mr",
  MARSHALLESE: "mh",
  MOLDAVIAN: "mo",
  MONGOLIAN: "mn",
  NAURU: "na",
  NAVAJO: "nv",
  NDONGA: "ng",
  "NORTHERN NDEBELE": "nd",
  NEPALI: "ne",
  NORWEGIAN: "no",
  "NORWEGIAN BOKMÅL": "nb",
  "NORWEGIAN NYNORSK": "nn",
  NUOSU: "ii",
  OCCITAN: "oc",
  OJIBWE: "oj",
  "OLD CHURCH SLAVONIC, OLD BULGARIAN": "cu",
  ORIYA: "or",
  "OROMO (AFAAN OROMO)": "om",
  OSSETIAN: "os",
  PĀLI: "pi",
  "PASHTO, PUSHTO": "ps",
  "PERSIAN (FARSI)": "fa",
  POLISH: "pl",
  PORTUGUESE: "pt",
  "PUNJABI (EASTERN)": "pa",
  QUECHUA: "qu",
  ROMANSH: "rm",
  ROMANIAN: "ro",
  RUSSIAN: "ru",
  SAMI: "se",
  SAMOAN: "sm",
  SANGO: "sg",
  SANSKRIT: "sa",
  SERBIAN: "sr",
  "SERBO-CROATIAN": "sh",
  SESOTHO: "st",
  SETSWANA: "tn",
  SHONA: "sn",
  "SICHUAN YI": "ii",
  SINDHI: "sd",
  SINHALESE: "si",
  SISWATI: "ss",
  SLOVAK: "sk",
  SLOVENIAN: "sl",
  SOMALI: "so",
  "SOUTHERN NDEBELE": "nr",
  SPANISH: "es",
  SUNDANESE: "su",
  "SWAHILI (KISWAHILI)": "sw",
  SWATI: "ss",
  SWEDISH: "sv",
  TAGALOG: "tl",
  TAHITIAN: "ty",
  TAJIK: "tg",
  TAMIL: "ta",
  TATAR: "tt",
  TELUGU: "te",
  THAI: "th",
  TIBETAN: "bo",
  TIGRINYA: "ti",
  TONGA: "to",
  TSONGA: "ts",
  TURKISH: "tr",
  TURKMEN: "tk",
  TWI: "tw",
  UYGHUR: "ug",
  UKRAINIAN: "uk",
  URDU: "ur",
  UZBEK: "uz",
  VENDA: "ve",
  VIETNAMESE: "vi",
  VOLAPÜK: "vo",
  WALLON: "wa",
  WELSH: "cy",
  WOLOF: "wo",
  "WESTERN FRISIAN": "fy",
  XHOSA: "xh",
  YIDDISH: "yi, ji",
  YORUBA: "yo",
  "ZHUANG, CHUANG": "za",
  ZULU: "zu",
} as const;
